yolo_node:
  ros__parameters:
    model: "yolo11m-seg.pt"  # Path to the YOLO model
    use_3d: true  # Enable 3D processing
    input_image_topic: "/camera/image/postprocessed"  # Topic for input RGB image
    input_depth_topic: "/camera/depth/raw"  # Topic for input depth image
    input_depth_info_topic: "/camera/camera_info"  # T opic for input depth camera info
    target_frame: "camera_link"  # Target frame for transformations
