# twist_mux.yaml

topics:
  - name: teleop
    topic: /joy_teleop/cmd_vel
    timeout: 0.5
    priority: 100

  - name: command
    topic: /commands/cmd_vel
    timeout: 0.5
    priority: 50


  - name: autonomous
    topic: /navigation/cmd_vel
    timeout: 0.5
    priority: 25


    



# Optional: topics that can enable/disable other topics
# buttons:
#   - name: emergency_stop
#     topic: /emergency_stop
#     short_key: 0

