// Generated by gencpp from file xbot/EncodersResponse.msg
// DO NOT EDIT!


#ifndef XBOT_MESSAGE_ENCODERSRESPONSE_H
#define XBOT_MESSAGE_ENCODERSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xbot
{
template <class ContainerAllocator>
struct EncodersResponse_
{
  typedef EncodersResponse_<ContainerAllocator> Type;

  EncodersResponse_()
    : enc1()
    , enc2()  {
    }
  EncodersResponse_(const ContainerAllocator& _alloc)
    : enc1(_alloc)
    , enc2(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _enc1_type;
  _enc1_type enc1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _enc2_type;
  _enc2_type enc2;




  typedef boost::shared_ptr< ::xbot::EncodersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xbot::EncodersResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EncodersResponse_

typedef ::xbot::EncodersResponse_<std::allocator<void> > EncodersResponse;

typedef boost::shared_ptr< ::xbot::EncodersResponse > EncodersResponsePtr;
typedef boost::shared_ptr< ::xbot::EncodersResponse const> EncodersResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xbot::EncodersResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xbot::EncodersResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xbot::EncodersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xbot::EncodersResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbot::EncodersResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbot::EncodersResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbot::EncodersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbot::EncodersResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xbot::EncodersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67a83120b6a9a148d594f8ed47a7b34d";
  }

  static const char* value(const ::xbot::EncodersResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67a83120b6a9a148ULL;
  static const uint64_t static_value2 = 0xd594f8ed47a7b34dULL;
};

template<class ContainerAllocator>
struct DataType< ::xbot::EncodersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xbot/EncodersResponse";
  }

  static const char* value(const ::xbot::EncodersResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xbot::EncodersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string enc1\n\
string enc2\n\
\n\
";
  }

  static const char* value(const ::xbot::EncodersResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xbot::EncodersResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enc1);
      stream.next(m.enc2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct EncodersResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xbot::EncodersResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xbot::EncodersResponse_<ContainerAllocator>& v)
  {
    s << indent << "enc1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.enc1);
    s << indent << "enc2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.enc2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XBOT_MESSAGE_ENCODERSRESPONSE_H
