<?xml version="1.0"?>
<package format="3">
  <name>wetexplorer_control</name>
  <version>0.0.0</version>
  <description>WetExplorer Control Package</description>

  <maintainer email="someone@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies needed at build and runtime -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend> 
  <depend>wetexplorer_description</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>teleop_twist_joy</depend>
  <depend>twist_mux</depend>
  <depend>joy</depend>
  <depend>interactive_marker_twist_server</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
