yolo_node:
  ros__parameters:
    model: "/workspaces/ros2_ws/src/wetexplorer/wetexplorer_perception/models/object_recognition_V4_01/11n.pt"  # Path to the YOLO model
    use_3d: true  # Enable 3D processing
    input_image_topic: "/camera/color/image_raw"  # Topic for input RGB image
    input_depth_topic: "/camera/depth/image_raw"  # Topic for input depth image
    input_depth_info_topic: "/camera/depth/camera_info"  # T opic for input depth camera info
    target_frame: "camera_link"  # Target frame for transformations
    threshold: "0.9"

