# Base controller configuration
controller_manager:
  ros__parameters:
    update_rate: 100 # Frequency of the controller updates in Hz

# Velocity controllers for rear wheels
rear_left_wheel_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "rear_left_wheel_joint"
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0

rear_right_wheel_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "rear_right_wheel_joint"
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0

# Velocity controllers for front wheels
front_left_wheel_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "front_left_wheel_joint"
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0

front_right_wheel_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "front_right_wheel_joint"
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0

# Example of a joint state controller to publish joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50  # Frequency of publishing joint states

# Example of a robot state publisher
robot_state_publisher:
  type: "robot_state_publisher/RobotStatePublisher"
  publish_frequency: 100  # Frequency of publishing robot states
